### ISSUE TITLE
指针的问题

### ISSUE THREAD

**Issue by thewaterislo** [liufushihai/Qt_WireShark#2]
链表的指针不用释放吗

**Comment by Fujihai** [comment]
> 链表的指针不用释放吗

正常来说是要的，这个项目是以前上学时候写的，仅供参考哈，好多实现细节并不是很完善的~

**Comment by thewaterislo** [comment]
谢谢你的回复，我也是学习，参考你的在windows上面写:) @FujiHai

**Comment by Fujihai** [comment]
> 谢谢你的回复，我也是学习，参考你的在windows上面写:) @FujiHai

赞！期待你的作品😁。
